app:
  name: camera-controller-mwir
  log_level: debug
  api:
    api_type: grpc
    server_address: 0.0.0.0:50052
  core:
    camera: core
  infrastructure:
    camera: mwir
    video_channel: 2
    endpoints:
      - address: frontier-mwir-mpsoc.local:3016