app:
  name: mwir
  log_level: debug
  api:
    api_type: grpc
    server_address: 0.0.0.0:50051
  core:
    camera: core
  infrastructure:
    camera: mwir
    endpoints:
      - address: 192.168.1.51:2017