syntax = "proto3";

package camera;

service CameraService {
  rpc SetZoom (SetZoomRequest) returns (SetZoomResponse) {}
  rpc GetZoom (GetZoomRequest) returns (GetZoomResponse) {}
  rpc SetFocus (SetFocusRequest) returns (SetFocusResponse) {}
  rpc GetFocus (GetFocusRequest) returns (GetFocusResponse) {}
  rpc GetInfo (GetInfoRequest) returns (GetInfoResponse) {}
}

message SetZoomRequest {
  uint32 zoom = 1;
}

message SetZoomResponse {
  uint32 zoom = 1;
}

message GetZoomRequest {
}

message GetZoomResponse {
  uint32 zoom = 1;
}

message SetFocusRequest {
  uint32 focus = 1;
}

message SetFocusResponse {
  uint32 focus = 1;
}

message GetFocusRequest {
}

message GetFocusResponse {
  uint32 focus = 1;
}

message GetInfoRequest {
}

message GetInfoResponse {
  string info = 1;
}